### ISSUE TITLE
Installing from nuget fails for project targeting .net framework lower than net46.

### ISSUE THREAD

**Issue by borisdj** [ethanli83/EFSqlTranslator#25] opened 2017-04-24 20:06 UTC
When trying to install package from nuget I am getting:
 _Package restore failed. Rolling back package changes for '...' 0_	

in .NetCore WebApi project with
Visual Studio 2017 targeting net452

**Comment by ethanli83** [comment] 2017-04-24 20:24
hi @borisdj, the package was created using old .net core project file format. Since everything has changed back to .csproj format, something may get broken. I will have a look at it today. 

Also, what is the target framework? The package only targets .netcoreapp, so if your project is targeting netcoreapp and net452, it may not work.

**Comment by borisdj** [comment] 2017-04-24 20:31
Problem is that my ASP.Net Core have (.Net Framework) target, because I use some others libraries that are not ported to Core yet.
I see now this one is Core only at the moment.
I just made new ASP.Net Core project (.Net Core) and it works.

In the following months .Net Standard 2.0 will be released.
Do you have plans to move code to that library format, since that way it will support both, .Net Core and .Net Framework ?

**Comment by ethanli83** [comment] 2017-04-24 20:49
I did not know about .net standard 2.0, but I do have a plan to make the package to support both core and .net framework. If the new format makes everything easier, I will definitely move to it.

I will be working on getting the library to target .net framework first, and close this issue once it is down. Just keep eyes on this issue :simple_smile:.

**Comment by borisdj** [comment] 2017-04-24 21:34
At the moment to support both you need to double it and have 2 nugets, bad redundancy.
With Standard 2.0 one will rule them all.
[https://weblog.west-wind.com/posts/2016/Nov/23/NET-Standard-20-Making-Sense-of-NET-Again](https://weblog.west-wind.com/posts/2016/Nov/23/NET-Standard-20-Making-Sense-of-NET-Again)
[https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/)
[https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates](https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates)

**Comment by ethanli83** [comment] 2017-04-25 03:49
hi @borisdj, I just release a new version which is targeting netstandard1.3. It should support net45 and higher.

The new versions are 1.2.2 for Translation package, and 1.1.1 for EFModels. Can u have a look when you are free? 

Also, I create a repo(https://github.com/ethanli83/EFSqlTranslatorExamples) and put some sample code. There are not much in there at the moment, I will put more samples in it later.

Thanks.

**Comment by borisdj** [comment] 2017-04-25 08:12
Still getting:
_Package restore failed. Rolling back package changes for 'Project'._
when trying to install from nuget in project with (.Net Framework) target.

**Comment by ethanli83** [comment] 2017-04-25 09:20
Interesting. I test it on net452 and net46, and it was working fine for me. Is there any change you can create a git repo with a sample project that I can test on it? 

Have you try using console to install it or even manually add the package in in project file?

Thanks

**Comment by borisdj** [comment] 2017-04-25 09:58
[Error screenshot ](https://www.dropbox.com/s/5kii2h4w38r75pj/nugetError.jpg?dl=0)
[Project sample](https://www.dropbox.com/s/mpm9hhd0wiqxd9r/TestApp.zip?dl=0)

**Comment by ethanli83** [comment] 2017-04-25 10:38
Looks like it only works on net46 at the moment.

**Comment by ethanli83** [comment] 2017-04-25 10:54
It turns out to be a bit difficlut to support netcore and net451 than I think. I cant use netstandard1.2, as EFCore did not support netstandard1.2, they targets net451 and netstandard1.3 separately. So I do need to target both frameworks as well. 

The problem is my build agent is a Linux machine, and my build only works with netcore or netstandard. So it will take longer to support both targets as I need to find a different build serivce that support windows. and I also need to learn MSBuild, kkk.

I may just wait for netstandard2.0, and see it that fixed the problem. For now, you may need to target net46 or netstandard1.3. 

Sorry for all the inconveniences.

**Comment by borisdj** [comment] 2017-04-25 13:03
No problem, as I already said:

> At the moment to support both you need to double it I think and have 2 nugets.

> With Standard 2.0 one will rule them all.

They made a little mess with these versions, and only with 2.0 there will be option to make one library that will work on latest versions of both .NetCore and .NetFramework.
So it's OK to wait for it.
We'll be in touch after they release it.

**Comment by ethanli83** [comment] 2017-04-25 21:35
Thanks. 

The good thing is I have cleaned up most dependencies, so it should be very straightforward to upgrade to netstandard2.0 once it arrives. 

And it works for net46 now. kk

**Comment by borisdj** [comment] 2017-04-26 08:35
I actually didn't notice the target version.
I thought that when creating project in VS2017 default version would be the latest, but it seems that the default version is 4.5.2.
I have no obstacle in changing it to 4.6 which I did and now nuget can be installed.
Thx for pointing to that info.

**Comment by ethanli83** [comment] 2017-04-26 08:40
Awsome~ Let me know if you have any other problem. Cheers.

**Comment by ethanli83** [comment] 2017-08-25 21:30
Hi @borisdj, 

I have pushed two nuget packages ([Translation-1.3.0-rc1](https://www.nuget.org/packages/EFSqlTranslator.Translation/1.3.0-rc1) and [EFModels-1.2.0-rc1](https://www.nuget.org/packages/EFSqlTranslator.EFModels/1.2.0-rc1)) which support netstandard2.0. You could try them out, and see if they work for you. 

Let me know if there is any problem. If they work fine, I will push them as actual releases.

Thanks

**Comment by borisdj** [comment] 2017-08-28 10:15
I have managed to install packages in NetCore2.0 project that is using EFCore2.0 but when GroupBy is executed I got the following Error:

> Message:	"Value cannot be null.\r\nParameter name: key"

StackTrace:
```"at System.Collections.Concurrent.ConcurrentDictionary`2.TryAdd(TKey key, TValue value)\r\n   at EFSqlTranslator.EFModels.EFModelInfoProvider.UpdateKeysAndColumns(IEntityType et, EntityInfo ei)\r\n   at EFSqlTranslator.EFModels.EFModelInfoProvider..ctor(DbContext context)\r\n   at Tyroll.Data.Repositories.UserTypeRepository.GroupByLibExample()\r\n   at Tyroll.Controllers.UserTypesController.GroupBy()\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()"```

**Comment by ethanli83** [comment] 2017-08-28 21:29
Hi @borisdj,

Looks like EFCore can not provide propertyInfo(IProperty.PropertyInfo) on an entity in the data model. If you did not have this issue with last release of my library and EFCore1.0, it will mean that there is a problem with EFCore2.0 as I did not change anything functionally. 

Also, I could not replicate this issue locally. So do you mind to see if you can replicate this issue with some simple data model? It will help me to fix this problem.

Thanks

**Comment by ethanli83** [comment] 2017-08-28 22:47
Hi @borisdj,

I just pushed some changes in Translation-1.3.0-rc2 and EFModels-1.2.0-rc2, can you try and see if they fix the issue for you? 

If not, I may need your help to create a simple code replicating the issue, so I can find the problem.

Thx,

**Comment by borisdj** [comment] 2017-08-29 11:01
I loaded source code of libraries into the project for more detailed debugging and I have found out what caused this issue.
It is Not the bug from libraries but in the FK of Entity.
I had a junction table with it's PK and 2 FKs that are configured by Convention, which all are **Guid**-s but one was wrongly **int** type.
```
public class MainTable
{
    public Guid MainTableId { get; set; }

    public Guid FirstTableId { get; set; }
    
    public int SecondTableId { get; set; }
                    
    public int Order { get; set; }

    public virtual FirstTable FirstTable { get; set; }

    public virtual SecondTable SecondTable { get; set; }
}
public class SecondTable 
{
    public Guid SecondTableId { get; set; }
}
```
Mistake was in line `public int SecondTableId { get; set; }` it should have been _Guid_, not _int_.
And since `virtual SecondTable` defines FK and tries to create column by convention(TableNameId) _Guid SecondTableId_ but it's same name as _int SecondTableId_ so it creates FK column in Db with name _Guid SecondTableId1_ (adds number 1 sufix).

Additionally what I was not aware of is that your library loads all columns into this dictionary.
I have tried GroupBy with 2 tables and this FK bug was on third table that had no direct connections with them.
So it would be good if you would take this situation and other similar, into the consideration, to skip error when it's not directly used or throw more specific exception that would be easier to debug.

The expcetion was thrown from:
`EFModelInfoProvider` class
`UpdateKeysAndColumns` method
`_fieldInfos.TryAdd(` line

**Comment by ethanli83** [comment] 2017-08-29 23:09
Hi @borisdj, 

Thanks for the detailed information, and the suggested solutions! 

I think the suggestion on better exception is a great one. Skipping on error may cause issues as the translator will need information about the column if the associated relation is used in queries. I think the exception with more details with help people to debug and correct their data context.

Now it will throw this error:
```
Error Message:
 System.Exception : Property 'MainTable.SecondTableId1' does not have meta data 'PropertyInfo'.
Please check if it is setup correctly in the data context. EF may generate this column by convention if it is associated with relations.
```

Also, I just released Translator-2.0.0 and EFModels2.0.0, you can move to it if you want to use netcore2.0

**Closed by ethanli83** 2017-08-29 23:09 UTC
Labels: bug

**Comment by borisdj** [comment] 2017-08-30 07:47
Glad to be of assistance.
I have now tried 2.0.0 versions and they work fine.

**Comment by ethanli83** [comment] 2017-08-30 20:28
Great, thanks!
